spring:
    data:
        mongodb:
            normal:
                database: zjb
                host: ${aliyun.server}
                port: 27017
                username: admin
                password: 123
            message:
                database: message
                host: ${aliyun.server}
                port: 27017
                username: admin
                password: 123
spring:
    kafka:
        consumer:
            group-id: messageGroup
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
