spring:
    kafka:
        consumer:
            group-id: teamGroup
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
