server:
  port: 8082
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/goying666/zujuba-config/
          username: 13040837899@163.com
          password: code666.
          search-paths: config-repo/{application}
eureka:
  server:
    url: localhost
    port: 1111
  client:
    service-url:
      defaultZone: http://${eureka.server.url}:${eureka.server.port}/eureka/